
[34m[1mwandb[39m[22m: [33mWARNING[39m The save_model argument by default saves the model in the HDF5 format that cannot save custom objects like subclassed models and custom layers. This behavior will be deprecated in a future release in favor of the SavedModel format. Meanwhile, the HDF5 model is saved as W&B files and the SavedModel as W&B Artifacts.
Epoch 1/30

79/79 [==============================] - 11s 82ms/step - loss: 0.6925 - mean_absolute_error: 0.1376 - val_loss: 0.6914 - val_mean_absolute_error: 0.1278 - lr: 1.0000e-04
Epoch 2/30

79/79 [==============================] - 3s 38ms/step - loss: 0.6879 - mean_absolute_error: 0.1314 - val_loss: 0.6817 - val_mean_absolute_error: 0.1147 - lr: 1.0000e-04
Epoch 3/30
79/79 [==============================] - 3s 37ms/step - loss: 0.6619 - mean_absolute_error: 0.0964 - val_loss: 0.6468 - val_mean_absolute_error: 0.0622 - lr: 1.0000e-04
Epoch 4/30

79/79 [==============================] - 3s 38ms/step - loss: 0.6340 - mean_absolute_error: 0.0514 - val_loss: 0.6364 - val_mean_absolute_error: 0.0431 - lr: 1.0000e-04
Epoch 5/30
79/79 [==============================] - 3s 38ms/step - loss: 0.6288 - mean_absolute_error: 0.0415 - val_loss: 0.6345 - val_mean_absolute_error: 0.0385 - lr: 1.0000e-04
Epoch 6/30

79/79 [==============================] - 3s 37ms/step - loss: 0.6277 - mean_absolute_error: 0.0390 - val_loss: 0.6339 - val_mean_absolute_error: 0.0370 - lr: 1.0000e-04
Epoch 7/30
79/79 [==============================] - 3s 37ms/step - loss: 0.6271 - mean_absolute_error: 0.0378 - val_loss: 0.6334 - val_mean_absolute_error: 0.0361 - lr: 1.0000e-04
Epoch 8/30

79/79 [==============================] - 3s 37ms/step - loss: 0.6267 - mean_absolute_error: 0.0367 - val_loss: 0.6331 - val_mean_absolute_error: 0.0354 - lr: 1.0000e-04
Epoch 9/30
79/79 [==============================] - 3s 36ms/step - loss: 0.6262 - mean_absolute_error: 0.0354 - val_loss: 0.6327 - val_mean_absolute_error: 0.0340 - lr: 1.0000e-04
Epoch 10/30
79/79 [==============================] - 3s 36ms/step - loss: 0.6258 - mean_absolute_error: 0.0342 - val_loss: 0.6325 - val_mean_absolute_error: 0.0336 - lr: 1.0000e-04
Epoch 11/30
79/79 [==============================] - 3s 37ms/step - loss: 0.6254 - mean_absolute_error: 0.0330 - val_loss: 0.6319 - val_mean_absolute_error: 0.0311 - lr: 1.0000e-04
Epoch 12/30
29/79 [==========>...................] - ETA: 1s - loss: 0.6262 - mean_absolute_error: 0.0318
Traceback (most recent call last):
  File "/home/jean-sebastien/Documents/s7/PMC/PMC/src/machine_learning/un_supervised/neural_network/./train.py", line 180, in <module>
    history = train_model.train_hp(args.EPOCHS_HP, args.NUM_TRIALS_HP, args.EXECUTION_PER_TRIAL_HP, args.PATH_RESULTS)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jean-sebastien/Documents/s7/PMC/PMC/src/machine_learning/un_supervised/neural_network/./train.py", line 123, in train_hp
    hp_search = hp_tuner_instance.get_hp_search(args.HP_SEARCH, args.HP_NAME)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jean-sebastien/Documents/s7/PMC/PMC/src/machine_learning/un_supervised/neural_network/hyper_parameters_tuner.py", line 149, in get_hp_search
    self.tuner_search(tuner, self.callbacks[1:])
  File "/home/jean-sebastien/Documents/s7/PMC/PMC/src/machine_learning/un_supervised/neural_network/hyper_parameters_tuner.py", line 131, in tuner_search
    tuner.search(
  File "/home/jean-sebastien/Documents/s7/PMC/venv/lib/python3.11/site-packages/keras_tuner/engine/base_tuner.py", line 210, in search
    self._try_run_and_update_trial(trial, *fit_args, **fit_kwargs)
  File "/home/jean-sebastien/Documents/s7/PMC/venv/lib/python3.11/site-packages/keras_tuner/engine/base_tuner.py", line 250, in _try_run_and_update_trial
    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)
  File "/home/jean-sebastien/Documents/s7/PMC/venv/lib/python3.11/site-packages/keras_tuner/engine/base_tuner.py", line 215, in _run_and_update_trial
    results = self.run_trial(trial, *fit_args, **fit_kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jean-sebastien/Documents/s7/PMC/PMC/src/machine_learning/un_supervised/neural_network/hyper_parameters_tuner.py", line 68, in run_trial
    history = model.fit(
      ^^^^^^^^^^^^^^^^^^
  File "/home/jean-sebastien/Documents/s7/PMC/venv/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py", line 65, in error_handler
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/jean-sebastien/Documents/s7/PMC/venv/lib/python3.11/site-packages/keras/src/engine/training.py", line 1807, in fit
    tmp_logs = self.train_function(iterator)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jean-sebastien/Documents/s7/PMC/venv/lib/python3.11/site-packages/tensorflow/python/util/traceback_utils.py", line 150, in error_handler
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/jean-sebastien/Documents/s7/PMC/venv/lib/python3.11/site-packages/tensorflow/python/eager/polymorphic_function/polymorphic_function.py", line 832, in __call__
    result = self._call(*args, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jean-sebastien/Documents/s7/PMC/venv/lib/python3.11/site-packages/tensorflow/python/eager/polymorphic_function/polymorphic_function.py", line 868, in _call
    return tracing_compilation.call_function(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jean-sebastien/Documents/s7/PMC/venv/lib/python3.11/site-packages/tensorflow/python/eager/polymorphic_function/tracing_compilation.py", line 139, in call_function
    return function._call_flat(  # pylint: disable=protected-access
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jean-sebastien/Documents/s7/PMC/venv/lib/python3.11/site-packages/tensorflow/python/eager/polymorphic_function/concrete_function.py", line 1323, in _call_flat
    return self._inference_function.call_preflattened(args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jean-sebastien/Documents/s7/PMC/venv/lib/python3.11/site-packages/tensorflow/python/eager/polymorphic_function/atomic_function.py", line 216, in call_preflattened
    flat_outputs = self.call_flat(*args)
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jean-sebastien/Documents/s7/PMC/venv/lib/python3.11/site-packages/tensorflow/python/eager/polymorphic_function/atomic_function.py", line 251, in call_flat
    outputs = self._bound_context.call_function(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jean-sebastien/Documents/s7/PMC/venv/lib/python3.11/site-packages/tensorflow/python/eager/context.py", line 1486, in call_function
    outputs = execute.execute(
              ^^^^^^^^^^^^^^^^
  File "/home/jean-sebastien/Documents/s7/PMC/venv/lib/python3.11/site-packages/tensorflow/python/eager/execute.py", line 53, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
79/79 [==============================] - 3s 37ms/step - loss: 0.6250 - mean_absolute_error: 0.0314 - val_loss: 0.6316 - val_mean_absolute_error: 0.0300 - lr: 1.0000e-04
Epoch 13/30
 1/79 [..............................] - ETA: 3s - loss: 0.5877 - mean_absolute_error: 0.0309