
Epoch 1/30


59/59 [==============================] - ETA: 0s - loss: 0.6447 - mean_absolute_error: 0.0712
/home/jean-sebastien/Documents/s7/PMC/venv/lib/python3.11/site-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(
59/59 [==============================] - 11s 108ms/step - loss: 0.6447 - mean_absolute_error: 0.0712 - val_loss: 0.6329 - val_mean_absolute_error: 0.0348
Epoch 2/30
59/59 [==============================] - 3s 46ms/step - loss: 0.6259 - mean_absolute_error: 0.0364 - val_loss: 0.6346 - val_mean_absolute_error: 0.0470
Epoch 3/30
45/59 [=====================>........] - ETA: 0s - loss: 0.6242 - mean_absolute_error: 0.0358
/home/jean-sebastien/Documents/s7/PMC/venv/lib/python3.11/site-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.

59/59 [==============================] - ETA: 0s - loss: 0.6252 - mean_absolute_error: 0.0347
59/59 [==============================] - 4s 71ms/step - loss: 0.6252 - mean_absolute_error: 0.0347 - val_loss: 0.6311 - val_mean_absolute_error: 0.0301
Epoch 4/30
40/59 [===================>..........] - ETA: 0s - loss: 0.6246 - mean_absolute_error: 0.0370
/home/jean-sebastien/Documents/s7/PMC/venv/lib/python3.11/site-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.

58/59 [============================>.] - ETA: 0s - loss: 0.6251 - mean_absolute_error: 0.0348
59/59 [==============================] - 4s 73ms/step - loss: 0.6251 - mean_absolute_error: 0.0348 - val_loss: 0.6307 - val_mean_absolute_error: 0.0282
Epoch 5/30
59/59 [==============================] - 3s 47ms/step - loss: 0.6241 - mean_absolute_error: 0.0307 - val_loss: 0.6310 - val_mean_absolute_error: 0.0301
Epoch 6/30
59/59 [==============================] - 3s 46ms/step - loss: 0.6238 - mean_absolute_error: 0.0297 - val_loss: 0.6316 - val_mean_absolute_error: 0.0333
Epoch 7/30

47/59 [======================>.......] - ETA: 0s - loss: 0.6229 - mean_absolute_error: 0.0279
/home/jean-sebastien/Documents/s7/PMC/venv/lib/python3.11/site-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.

59/59 [==============================] - ETA: 0s - loss: 0.6235 - mean_absolute_error: 0.0281
59/59 [==============================] - 4s 70ms/step - loss: 0.6235 - mean_absolute_error: 0.0281 - val_loss: 0.6302 - val_mean_absolute_error: 0.0264
Epoch 8/30
59/59 [==============================] - 3s 47ms/step - loss: 0.6237 - mean_absolute_error: 0.0290 - val_loss: 0.6303 - val_mean_absolute_error: 0.0265
Epoch 9/30
59/59 [==============================] - 3s 46ms/step - loss: 0.6232 - mean_absolute_error: 0.0270 - val_loss: 0.6347 - val_mean_absolute_error: 0.0484
Epoch 10/30

55/59 [==========================>...] - ETA: 0s - loss: 0.6239 - mean_absolute_error: 0.0301
/home/jean-sebastien/Documents/s7/PMC/venv/lib/python3.11/site-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
59/59 [==============================] - 4s 71ms/step - loss: 0.6238 - mean_absolute_error: 0.0300 - val_loss: 0.6298 - val_mean_absolute_error: 0.0246
Epoch 11/30
 5/59 [=>............................] - ETA: 2s - loss: 0.6291 - mean_absolute_error: 0.0263

49/59 [=======================>......] - ETA: 0s - loss: 0.6224 - mean_absolute_error: 0.0256
/home/jean-sebastien/Documents/s7/PMC/venv/lib/python3.11/site-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.

59/59 [==============================] - ETA: 0s - loss: 0.6229 - mean_absolute_error: 0.0260
59/59 [==============================] - 4s 70ms/step - loss: 0.6229 - mean_absolute_error: 0.0260 - val_loss: 0.6297 - val_mean_absolute_error: 0.0242
Epoch 12/30
59/59 [==============================] - 3s 47ms/step - loss: 0.6228 - mean_absolute_error: 0.0256 - val_loss: 0.6298 - val_mean_absolute_error: 0.0249
Epoch 13/30

59/59 [==============================] - ETA: 0s - loss: 0.6229 - mean_absolute_error: 0.0259
/home/jean-sebastien/Documents/s7/PMC/venv/lib/python3.11/site-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(
59/59 [==============================] - 4s 72ms/step - loss: 0.6229 - mean_absolute_error: 0.0259 - val_loss: 0.6296 - val_mean_absolute_error: 0.0237
Epoch 14/30
59/59 [==============================] - 3s 49ms/step - loss: 0.6235 - mean_absolute_error: 0.0288 - val_loss: 0.6316 - val_mean_absolute_error: 0.0351
Epoch 15/30

59/59 [==============================] - 3s 48ms/step - loss: 0.6232 - mean_absolute_error: 0.0270 - val_loss: 0.6303 - val_mean_absolute_error: 0.0284
Epoch 16/30
59/59 [==============================] - 3s 47ms/step - loss: 0.6227 - mean_absolute_error: 0.0251 - val_loss: 0.6299 - val_mean_absolute_error: 0.0266
Epoch 17/30

59/59 [==============================] - ETA: 0s - loss: 0.6227 - mean_absolute_error: 0.0251
/home/jean-sebastien/Documents/s7/PMC/venv/lib/python3.11/site-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(
59/59 [==============================] - 4s 71ms/step - loss: 0.6227 - mean_absolute_error: 0.0251 - val_loss: 0.6294 - val_mean_absolute_error: 0.0232
Epoch 18/30


59/59 [==============================] - 3s 46ms/step - loss: 0.6228 - mean_absolute_error: 0.0261 - val_loss: 0.6295 - val_mean_absolute_error: 0.0240
Epoch 19/30
59/59 [==============================] - 3s 46ms/step - loss: 0.6225 - mean_absolute_error: 0.0242 - val_loss: 0.6296 - val_mean_absolute_error: 0.0248
Epoch 20/30
59/59 [==============================] - 3s 46ms/step - loss: 0.6244 - mean_absolute_error: 0.0323 - val_loss: 0.6299 - val_mean_absolute_error: 0.0255
Epoch 21/30

59/59 [==============================] - 3s 47ms/step - loss: 0.6227 - mean_absolute_error: 0.0246 - val_loss: 0.6296 - val_mean_absolute_error: 0.0241
Epoch 22/30
35/59 [================>.............] - ETA: 1s - loss: 0.6227 - mean_absolute_error: 0.0236
/home/jean-sebastien/Documents/s7/PMC/venv/lib/python3.11/site-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.

59/59 [==============================] - ETA: 0s - loss: 0.6225 - mean_absolute_error: 0.0235
59/59 [==============================] - 4s 71ms/step - loss: 0.6225 - mean_absolute_error: 0.0235 - val_loss: 0.6293 - val_mean_absolute_error: 0.0233
Epoch 23/30

59/59 [==============================] - ETA: 0s - loss: 0.6225 - mean_absolute_error: 0.0245
/home/jean-sebastien/Documents/s7/PMC/venv/lib/python3.11/site-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(
59/59 [==============================] - 4s 72ms/step - loss: 0.6225 - mean_absolute_error: 0.0245 - val_loss: 0.6293 - val_mean_absolute_error: 0.0226
Epoch 24/30
59/59 [==============================] - 3s 47ms/step - loss: 0.6230 - mean_absolute_error: 0.0258 - val_loss: 0.6330 - val_mean_absolute_error: 0.0428
Epoch 25/30

55/59 [==========================>...] - ETA: 0s - loss: 0.6227 - mean_absolute_error: 0.0259
/home/jean-sebastien/Documents/s7/PMC/venv/lib/python3.11/site-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.

59/59 [==============================] - ETA: 0s - loss: 0.6228 - mean_absolute_error: 0.0257
59/59 [==============================] - 4s 72ms/step - loss: 0.6228 - mean_absolute_error: 0.0257 - val_loss: 0.6292 - val_mean_absolute_error: 0.0223
Epoch 26/30
51/59 [========================>.....] - ETA: 0s - loss: 0.6229 - mean_absolute_error: 0.0220
/home/jean-sebastien/Documents/s7/PMC/venv/lib/python3.11/site-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.

59/59 [==============================] - ETA: 0s - loss: 0.6221 - mean_absolute_error: 0.0221
59/59 [==============================] - 4s 70ms/step - loss: 0.6221 - mean_absolute_error: 0.0221 - val_loss: 0.6291 - val_mean_absolute_error: 0.0221
Epoch 27/30
59/59 [==============================] - 3s 46ms/step - loss: 0.6221 - mean_absolute_error: 0.0219 - val_loss: 0.6297 - val_mean_absolute_error: 0.0247
Epoch 28/30

59/59 [==============================] - ETA: 0s - loss: 0.6224 - mean_absolute_error: 0.0235
/home/jean-sebastien/Documents/s7/PMC/venv/lib/python3.11/site-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(
59/59 [==============================] - 4s 72ms/step - loss: 0.6224 - mean_absolute_error: 0.0235 - val_loss: 0.6290 - val_mean_absolute_error: 0.0210
Epoch 29/30
59/59 [==============================] - 3s 46ms/step - loss: 0.6219 - mean_absolute_error: 0.0209 - val_loss: 0.6290 - val_mean_absolute_error: 0.0212
Epoch 30/30


59/59 [==============================] - 3s 45ms/step - loss: 0.6224 - mean_absolute_error: 0.0231 - val_loss: 0.6309 - val_mean_absolute_error: 0.0307