
Epoch 1/30




1106/1106 [==============================] - ETA: 0s - loss: 0.6460 - mean_absolute_error: 0.0671
/home/jean-sebastien/Documents/s7/PMC/venv/lib/python3.11/site-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(
1106/1106 [==============================] - 12s 9ms/step - loss: 0.6460 - mean_absolute_error: 0.0671 - val_loss: 0.6320 - val_mean_absolute_error: 0.0326
Epoch 2/30



1105/1106 [============================>.] - ETA: 0s - loss: 0.6248 - mean_absolute_error: 0.0319
/home/jean-sebastien/Documents/s7/PMC/venv/lib/python3.11/site-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
1106/1106 [==============================] - 9s 8ms/step - loss: 0.6248 - mean_absolute_error: 0.0319 - val_loss: 0.6312 - val_mean_absolute_error: 0.0304
Epoch 3/30
 164/1106 [===>..........................] - ETA: 6s - loss: 0.6286 - mean_absolute_error: 0.0315



1097/1106 [============================>.] - ETA: 0s - loss: 0.6237 - mean_absolute_error: 0.0285
/home/jean-sebastien/Documents/s7/PMC/venv/lib/python3.11/site-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
1106/1106 [==============================] - 8s 8ms/step - loss: 0.6239 - mean_absolute_error: 0.0285 - val_loss: 0.6301 - val_mean_absolute_error: 0.0247
Epoch 4/30
 106/1106 [=>............................] - ETA: 7s - loss: 0.6212 - mean_absolute_error: 0.0259



1095/1106 [============================>.] - ETA: 0s - loss: 0.6227 - mean_absolute_error: 0.0230
/home/jean-sebastien/Documents/s7/PMC/venv/lib/python3.11/site-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
1106/1106 [==============================] - 8s 7ms/step - loss: 0.6228 - mean_absolute_error: 0.0230 - val_loss: 0.6293 - val_mean_absolute_error: 0.0206
Epoch 5/30
 110/1106 [=>............................] - ETA: 6s - loss: 0.6193 - mean_absolute_error: 0.0207



1103/1106 [============================>.] - ETA: 0s - loss: 0.6223 - mean_absolute_error: 0.0196
/home/jean-sebastien/Documents/s7/PMC/venv/lib/python3.11/site-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(
1106/1106 [==============================] - 9s 8ms/step - loss: 0.6221 - mean_absolute_error: 0.0196 - val_loss: 0.6289 - val_mean_absolute_error: 0.0185
Epoch 6/30



1101/1106 [============================>.] - ETA: 0s - loss: 0.6218 - mean_absolute_error: 0.0181
/home/jean-sebastien/Documents/s7/PMC/venv/lib/python3.11/site-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
1106/1106 [==============================] - 9s 8ms/step - loss: 0.6218 - mean_absolute_error: 0.0181 - val_loss: 0.6288 - val_mean_absolute_error: 0.0192
Epoch 7/30
 164/1106 [===>..........................] - ETA: 5s - loss: 0.6219 - mean_absolute_error: 0.0179



1099/1106 [============================>.] - ETA: 0s - loss: 0.6215 - mean_absolute_error: 0.0171
/home/jean-sebastien/Documents/s7/PMC/venv/lib/python3.11/site-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
1106/1106 [==============================] - 8s 7ms/step - loss: 0.6216 - mean_absolute_error: 0.0171 - val_loss: 0.6285 - val_mean_absolute_error: 0.0167
Epoch 8/30
 149/1106 [===>..........................] - ETA: 6s - loss: 0.6180 - mean_absolute_error: 0.0162



1095/1106 [============================>.] - ETA: 0s - loss: 0.6212 - mean_absolute_error: 0.0167
/home/jean-sebastien/Documents/s7/PMC/venv/lib/python3.11/site-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(
1106/1106 [==============================] - 9s 8ms/step - loss: 0.6215 - mean_absolute_error: 0.0166 - val_loss: 0.6284 - val_mean_absolute_error: 0.0162
Epoch 9/30



1099/1106 [============================>.] - ETA: 0s - loss: 0.6214 - mean_absolute_error: 0.0161
/home/jean-sebastien/Documents/s7/PMC/venv/lib/python3.11/site-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
1106/1106 [==============================] - 9s 8ms/step - loss: 0.6213 - mean_absolute_error: 0.0161 - val_loss: 0.6283 - val_mean_absolute_error: 0.0155
Epoch 10/30
  65/1106 [>.............................] - ETA: 8s - loss: 0.6161 - mean_absolute_error: 0.0153




1103/1106 [============================>.] - ETA: 0s - loss: 0.6213 - mean_absolute_error: 0.0157
/home/jean-sebastien/Documents/s7/PMC/venv/lib/python3.11/site-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
1106/1106 [==============================] - 9s 8ms/step - loss: 0.6213 - mean_absolute_error: 0.0157 - val_loss: 0.6282 - val_mean_absolute_error: 0.0154
Epoch 11/30
 227/1106 [=====>........................] - ETA: 5s - loss: 0.6171 - mean_absolute_error: 0.0152



1105/1106 [============================>.] - ETA: 0s - loss: 0.6212 - mean_absolute_error: 0.0154
/home/jean-sebastien/Documents/s7/PMC/venv/lib/python3.11/site-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(
1106/1106 [==============================] - 9s 8ms/step - loss: 0.6212 - mean_absolute_error: 0.0154 - val_loss: 0.6282 - val_mean_absolute_error: 0.0152
Epoch 12/30

1106/1106 [==============================] - 7s 7ms/step - loss: 0.6211 - mean_absolute_error: 0.0151 - val_loss: 0.6282 - val_mean_absolute_error: 0.0159
Epoch 13/30



1106/1106 [==============================] - 9s 8ms/step - loss: 0.6211 - mean_absolute_error: 0.0149 - val_loss: 0.6281 - val_mean_absolute_error: 0.0152
Epoch 14/30
 120/1106 [==>...........................] - ETA: 4s - loss: 0.6118 - mean_absolute_error: 0.0147
/home/jean-sebastien/Documents/s7/PMC/venv/lib/python3.11/site-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


1106/1106 [==============================] - 6s 6ms/step - loss: 0.6211 - mean_absolute_error: 0.0147 - val_loss: 0.6283 - val_mean_absolute_error: 0.0179
Epoch 15/30



1101/1106 [============================>.] - ETA: 0s - loss: 0.6211 - mean_absolute_error: 0.0145
/home/jean-sebastien/Documents/s7/PMC/venv/lib/python3.11/site-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
1106/1106 [==============================] - 7s 6ms/step - loss: 0.6210 - mean_absolute_error: 0.0145 - val_loss: 0.6280 - val_mean_absolute_error: 0.0147
Epoch 16/30
 325/1106 [=======>......................] - ETA: 3s - loss: 0.6226 - mean_absolute_error: 0.0142


1106/1106 [==============================] - 7s 7ms/step - loss: 0.6210 - mean_absolute_error: 0.0144 - val_loss: 0.6280 - val_mean_absolute_error: 0.0143
Epoch 17/30
  36/1106 [..............................] - ETA: 6s - loss: 0.6279 - mean_absolute_error: 0.0142
/home/jean-sebastien/Documents/s7/PMC/venv/lib/python3.11/site-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(



1106/1106 [==============================] - 7s 6ms/step - loss: 0.6210 - mean_absolute_error: 0.0142 - val_loss: 0.6280 - val_mean_absolute_error: 0.0152
Epoch 18/30



1094/1106 [============================>.] - ETA: 0s - loss: 0.6210 - mean_absolute_error: 0.0140
/home/jean-sebastien/Documents/s7/PMC/venv/lib/python3.11/site-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(
1106/1106 [==============================] - 7s 7ms/step - loss: 0.6209 - mean_absolute_error: 0.0140 - val_loss: 0.6279 - val_mean_absolute_error: 0.0139
Epoch 19/30


1106/1106 [==============================] - 6s 6ms/step - loss: 0.6209 - mean_absolute_error: 0.0140 - val_loss: 0.6280 - val_mean_absolute_error: 0.0150
Epoch 20/30



1099/1106 [============================>.] - ETA: 0s - loss: 0.6211 - mean_absolute_error: 0.0138
/home/jean-sebastien/Documents/s7/PMC/venv/lib/python3.11/site-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
1106/1106 [==============================] - 9s 8ms/step - loss: 0.6209 - mean_absolute_error: 0.0138 - val_loss: 0.6279 - val_mean_absolute_error: 0.0136
Epoch 21/30
 148/1106 [===>..........................] - ETA: 4s - loss: 0.6233 - mean_absolute_error: 0.0134



1097/1106 [============================>.] - ETA: 0s - loss: 0.6209 - mean_absolute_error: 0.0137
/home/jean-sebastien/Documents/s7/PMC/venv/lib/python3.11/site-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
1106/1106 [==============================] - 8s 7ms/step - loss: 0.6209 - mean_absolute_error: 0.0137 - val_loss: 0.6279 - val_mean_absolute_error: 0.0137
Epoch 22/30
 195/1106 [====>.........................] - ETA: 5s - loss: 0.6202 - mean_absolute_error: 0.0140



1103/1106 [============================>.] - ETA: 0s - loss: 0.6208 - mean_absolute_error: 0.0136
/home/jean-sebastien/Documents/s7/PMC/venv/lib/python3.11/site-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
1106/1106 [==============================] - 8s 7ms/step - loss: 0.6208 - mean_absolute_error: 0.0136 - val_loss: 0.6278 - val_mean_absolute_error: 0.0133
Epoch 23/30
 156/1106 [===>..........................] - ETA: 5s - loss: 0.6178 - mean_absolute_error: 0.0135



1106/1106 [==============================] - 7s 7ms/step - loss: 0.6208 - mean_absolute_error: 0.0135 - val_loss: 0.6278 - val_mean_absolute_error: 0.0136
Epoch 24/30



1100/1106 [============================>.] - ETA: 0s - loss: 0.6207 - mean_absolute_error: 0.0133
/home/jean-sebastien/Documents/s7/PMC/venv/lib/python3.11/site-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
1106/1106 [==============================] - 9s 8ms/step - loss: 0.6208 - mean_absolute_error: 0.0133 - val_loss: 0.6278 - val_mean_absolute_error: 0.0132
Epoch 25/30
  71/1106 [>.............................] - ETA: 6s - loss: 0.6166 - mean_absolute_error: 0.0138




1096/1106 [============================>.] - ETA: 0s - loss: 0.6206 - mean_absolute_error: 0.0133
/home/jean-sebastien/Documents/s7/PMC/venv/lib/python3.11/site-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(
1106/1106 [==============================] - 9s 8ms/step - loss: 0.6208 - mean_absolute_error: 0.0133 - val_loss: 0.6278 - val_mean_absolute_error: 0.0131
Epoch 26/30



1100/1106 [============================>.] - ETA: 0s - loss: 0.6209 - mean_absolute_error: 0.0131
/home/jean-sebastien/Documents/s7/PMC/venv/lib/python3.11/site-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
1106/1106 [==============================] - 8s 7ms/step - loss: 0.6208 - mean_absolute_error: 0.0131 - val_loss: 0.6278 - val_mean_absolute_error: 0.0130
Epoch 27/30
 248/1106 [=====>........................] - ETA: 5s - loss: 0.6185 - mean_absolute_error: 0.0131


1106/1106 [==============================] - 8s 7ms/step - loss: 0.6208 - mean_absolute_error: 0.0132 - val_loss: 0.6278 - val_mean_absolute_error: 0.0134
Epoch 28/30




1098/1106 [============================>.] - ETA: 0s - loss: 0.6209 - mean_absolute_error: 0.0131
/home/jean-sebastien/Documents/s7/PMC/venv/lib/python3.11/site-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
1106/1106 [==============================] - 9s 8ms/step - loss: 0.6208 - mean_absolute_error: 0.0131 - val_loss: 0.6278 - val_mean_absolute_error: 0.0129
Epoch 29/30
 173/1106 [===>..........................] - ETA: 5s - loss: 0.6204 - mean_absolute_error: 0.0133




1101/1106 [============================>.] - ETA: 0s - loss: 0.6209 - mean_absolute_error: 0.0130
/home/jean-sebastien/Documents/s7/PMC/venv/lib/python3.11/site-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(
1106/1106 [==============================] - 9s 8ms/step - loss: 0.6207 - mean_absolute_error: 0.0130 - val_loss: 0.6277 - val_mean_absolute_error: 0.0127
Epoch 30/30




1106/1106 [==============================] - 8s 7ms/step - loss: 0.6207 - mean_absolute_error: 0.0128 - val_loss: 0.6278 - val_mean_absolute_error: 0.0133